-- 코드를 입력하세요
SELECT TITLE,BOARD_ID,REPLY_ID,R.WRITER_ID,R.CONTENTS,DATE_FORMat(R.CREATED_DATE,'%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R USING(BOARD_ID)
WHERE B.CREATED_DATE LIKE '2022-10%'
order by CREATED_DATE asc,TITLE asc;